import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const __dir = dirname(fileURLToPath(import.meta.url));
export const ROOT = join(__dir, "..");
export const REPORTS_DIR = join(ROOT, "reports");
export const LOG_DIR = join(ROOT, "logs");

export async function bundleModule(name, entry) {
  mkdirSync(LOG_DIR, { recursive: true });
  const outfile = join(LOG_DIR, name + ".bundled.mjs");
  await build({
    entryPoints: [join(ROOT, entry)],
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node18",
    outfile,
    logLevel: "silent",
  });
  return import(outfile + "?v=" + Date.now() + "-" + name);
}

export function environmentNotes() {
  return {
    node: process.version,
    platform: process.platform,
    architecture: process.arch,
    networkEvaluation: process.env.OPENAI_EVAL === "1" ? "requested" : "not requested",
  };
}

export function percentile(values, fraction) {
  if (!values.length) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  return sorted[Math.min(sorted.length - 1, Math.floor((sorted.length - 1) * fraction))];
}

export function markdownReport(title, report) {
  const fence = String.fromCharCode(96).repeat(3);
  const lines = [
    "# " + title,
    "",
    "Generated: " + report.generatedAt,
    "",
    "## Summary",
    "",
    "- Cases: " + report.summary.caseCount,
    "- Passed: " + report.summary.passed,
    "- Failed: " + report.summary.failed,
    "- Network evaluation: " + (report.network?.status ?? "not applicable"),
    "",
    "## Environment",
    "",
    fence + "json",
    JSON.stringify(report.environment, null, 2),
    fence,
    "",
    "## Limitations",
    "",
    ...(report.limitations ?? []).map((item) => "- " + item),
    "",
    "## Full machine-readable result",
    "",
    "See the adjacent JSON report generated by the same command.",
    "",
  ];
  return lines.join("\n");
}

